# Expose Prometheus
prometheus:
  service:
    type: NodePort
    nodePort: 30090
    port: 9090
    targetPort: 9090

# Expose Grafana
grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30080
    port: 80
    targetPort: 3000
  ingress:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

# Optional: Disable Alertmanager if not needed
alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30093

# Optional: Minimal scraping config for fewer resources
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false

  # serviceMonitor:
  #   # If true, a ServiceMonitor CRD is created for a prometheus operator
  #   # https://github.com/prometheus-operator/prometheus-operator
  #   #
  #   enabled: true

  #   # Path to use for scraping metrics. Might be different if server.root_url is set
  #   # in grafana.ini
  #   path: "/metrics"