replicas: 1
singleNode: true

persistence:
  enabled: true
  size: 10Gi
  storageClass: gp2

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: "Admin123!"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"