apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: default
  labels:
    app: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: busybox:1.35
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)\",\"level\":\"info\",\"service\":\"log-generator\",\"message\":\"Application is running normally\",\"request_id\":\"req-$(date +%s)\",\"user_id\":\"user-$((RANDOM % 100))\"}"
              sleep 10
              echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)\",\"level\":\"warn\",\"service\":\"log-generator\",\"message\":\"High memory usage detected\",\"memory_usage\":\"$((RANDOM % 50 + 50))%\"}"
              sleep 15
              echo "{\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)\",\"level\":\"error\",\"service\":\"log-generator\",\"message\":\"Failed to connect to database\",\"error_code\":\"DB_CONN_001\",\"retry_count\":$((RANDOM % 3 + 1))\"}"
              sleep 20
            done
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
