apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hodr
  name: hodr
  namespace: fampay-hodr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hodr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hodr
    spec:
      containers:
      - name: hodr
        env:
        - name: HOST_ADDR
          value: 0.0.0.0:8080
        image: public.ecr.aws/q0k4e9h0/fampay-hodr:v1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      restartPolicy: Always
