{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-network-policy
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
  - Ingress
  - Egress
  
  # Ingress rules - what can connect TO hodr
  ingress:
  {{- if .Values.networkPolicy.allowIngress.fromALB }}
  # Allow ALB/Ingress Controller to reach hodr
  - ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}

  {{- if .Values.networkPolicy.allowIngress.fromBran }}
  # Allow Bran service to connect to Hodr
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.allowIngress.branNamespace }}
    - podSelector:
        matchLabels:
          app: bran
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}

  {{- if .Values.networkPolicy.allowIngress.fromPrometheus }}
  # Allow Prometheus to scrape metrics
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.allowIngress.prometheusNamespace | default "monitoring" }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}

  # Egress rules - what hodr can connect TO
  # NOTE: ONLY these connections are allowed, everything else blocked
  egress:
  {{- if .Values.networkPolicy.allowEgress.toDNS }}
  # Allow DNS resolution
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  {{- end }}

  {{- if .Values.networkPolicy.allowEgress.toExternal }}
  # Allow external API calls
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  {{- end }}

  # NO RULE FOR PORT 8000 to fampay-bran namespace
  # This should block connection to Bran
{{- end }}