apiVersion: v1
kind: Secret
metadata:
  name: opensearch-admin-password
  namespace: opensearch
  labels:
    app: opensearch
    component: security
type: Opaque
data:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: TXlTdHJvbmdQYXNzd29yZDEyMyE=