apiVersion: v2
name: observability
description: A Helm chart for observability stack without Prometheus Operator
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 7.0.19
    repository: https://grafana.github.io/helm-charts