
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      nodeSelector:
        karpenter.sh/nodepool: demo-app-nodepool
      tolerations:
        - key: app
          operator: Equal
          value: demo-app
          effect: NoSchedule
      containers:
      - name: demo-app
        image: public.ecr.aws/q0k4e9h0/karpenter:v1.0.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
