apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: demo-app-nodeclass
  namespace: karpenter
spec:
  amiFamily: "AL2"
  role: "KarpenterNodeInstanceProfile-fampay-eks-cluster"
  
  # Subnet discovery
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: fampay-eks-cluster
  
  # Security group discovery  
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: fampay-eks-cluster
  
  # AMI selection
  amiSelectorTerms:
    - tags:
        karpenter.sh/discovery: fampay-eks-cluster
  
  # EBS configuration
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        encrypted: true
        volumeSize: "20"
        deleteOnTermination: true
  
  # Tags for instances
  tags:
    env: demo
    Name: "karpenter-demo-node"
    Environment: "demo"
    ManagedBy: "karpenter"
    NodePool: "demo-app"