apiVersion: karpenter.k8s.aws/v1
kind: NodePool
metadata:
  name: demo-app-nodepool
  namespace: karpenter
spec:
  template:
    spec:
      # Node requirements
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t2.small", "t3.small", "t3.medium"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b", "us-east-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
      
      # Taints for dedicated demo-app nodes
      taints:
        - key: app
          value: demo-app
          effect: NoSchedule
      
      # Reference to NodeClass
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: demo-app-nodeclass
        group: karpenter.k8s.aws
        
  # Resource limits for this pool
  limits:
    cpu: "100"
    
  # Disruption settings
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 60s
    budgets:
    - nodes: "100%"