{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-network-policy
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
  - Ingress
  
  ingress:
  {{- if .Values.networkPolicy.allowALB }}
  # Allow ALB/External traffic (unfortunately needs to be permissive for ALB)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: "kube-system"  # ALB controller namespace
  - from: []  # Allow external load balancer IPs (ALB requirement)
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  
  {{- if .Values.networkPolicy.allowPrometheus }}
  # Allow Prometheus monitoring
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.prometheusNamespace | default "monitoring" }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  
  # NO rule for Hodr = Hodr BLOCKED from connecting to Bran
{{- end }}