{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-network-policy
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
  - Ingress
  
  ingress:
  {{- if .Values.networkPolicy.allowPrometheus }}
  # Allow Prometheus monitoring
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: "monitoring"
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
  
  # REMOVED permissive ALB rule - let's see if external access still works
  # NO OTHER RULES = Block Hodr
{{- end }}