{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-network-policy
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
  - Ingress
  # NO Egress restrictions = allow all outgoing
  
  ingress:
  # Allow ALL incoming traffic (ALB requirement)
  - ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  
  {{- if .Values.networkPolicy.allowPrometheus }}
  # Allow Prometheus monitoring (redundant but explicit)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.networkPolicy.prometheusNamespace | default "observability" }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  {{- end }}
{{- end }}