apiVersion: v1
kind: Secret
metadata:
  namespace: fampay-bran
  name: bran-secrets
type: Opaque
stringData:
  SECRET_KEY: django-insecure-8j=hrs#^z0t%#1^89isbgqeddf2_zw!#zh45rz-=h&u%ze)o3e
  ALLOWED_HOSTS: "*"
  DEBUG: "true"
  TIME_ZONE: "UTC"
  DATABASE_URL: "postgres://akash:akashpass@postgres-db-svc:5432/fampay"
