apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Values.app.name }}-secrets
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey }}
  ALLOWED_HOSTS: {{ .Values.secrets.allowedHosts }}
  DEBUG: {{ .Values.secrets.debug }}
  TIME_ZONE: {{ .Values.secrets.timeZone }}
  DATABASE_URL: "postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.name }}-svc:{{ .Values.database.port }}/{{ .Values.database.dbName }}"