kube-prometheus-stack:
  # Prometheus configuration
  prometheus:
    prometheusSpec:
      resources:
        requests:
          memory: "250M"
          cpu: "100m"
        limits:
          memory: "600M"
          cpu: "200m"
      
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "gp2"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      
      retention: 30d
      retentionSize: 20GB
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
  
  # Enable Grafana within this chart
  grafana:
    enabled: true  # ✅ Change this to true
    
    # Grafana configuration
    adminPassword: "admin123"
    
    persistence:
      enabled: true
      storageClassName: "gp2"
      size: 10Gi
      accessModes:
        - ReadWriteOnce
    
    resources:
      requests:
        memory: "200Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "200m"
    
    # Pre-configured dashboards
    dashboards:
      default:
        kubernetes-cluster-monitoring:
          gnetId: 7249
          revision: 1
          datasource: Prometheus
        kubernetes-pod-monitoring:
          gnetId: 6417
          revision: 1
          datasource: Prometheus
        node-exporter:
          gnetId: 1860
          revision: 37
          datasource: Prometheus
  
  # AlertManager
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "500Mi"
          cpu: "200m"
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: "gp2"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
  
  nodeExporter:
    enabled: false
  
  kubeStateMetrics:
    enabled: true