# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: karpenter-resources
#   namespace: argocd
#   labels:
#     app: karpenter-resources
#     environment: demo
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/akash202k/fampay-solution  # Update this to your repo
#     path: deployments/helm-charts/karpenter-resources
#     targetRevision: HEAD
#     helm: {}
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: karpenter
  
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
    
#   # Health checks
#   # ignoreDifferences:
#   #   - group: karpenter.sh
#   #     kind: NodePool
#   #     jsonPointers:
#   #       - /status
#   #   - group: karpenter.k8s.aws
#   #     kind: EC2NodeClass  
#   #     jsonPointers:
#   #       - /status