apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  labels:
    app: observability
    environment: observability
spec:
  project: default
  source:
    repoURL: https://github.com/akash202k/fampay-solution  # Update this
    path: deployments/helm-charts/observability
    targetRevision: HEAD
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true