apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
  labels:
    app: opensearch
    environment: logging

spec:
  project: default  # Fixed: was 'observability' but that project may not exist/
  source:
    repoURL: https://github.com/akash202k/fampay-solution 
    path: deployments/helm-charts/observability/logging/os
    targetRevision: HEAD
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch  # Fixed: OpenSearch should be in 'opensearch' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      