apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-ingress
  namespace: argocd
  labels:
    app: shared-ingress
    environment: shared
spec:
  project: default
  source:
    repoURL: https://github.com/akash202k/fampay-solution
    path: deployments/helm-charts/shared-ingress
    targetRevision: HEAD
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: fampay-ingress
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true