# Chart.yaml for Grafana
apiVersion: v2
name: grafana
description: A Helm chart to deploy Grafana dashboard
type: application
version: 0.1.0
appVersion: "10.2.0"
dependencies:
  - name: grafana
    version: 7.3.7
    repository: https://grafana.github.io/helm-charts